### ISSUE TITLE
completely useless buttons that do nothing and not appearing dropdown menus

### ISSUE THREAD

**Issue by Mali357** [thistlecafe/cosmic-cat#100]
so there are a few things that are i guess just placeholders or are a bug, idk.
starting off with the bottom of the page:
undefined is present, also no dropdown menu, the same with english and safety options, being not funcional.
![nothing bro y](https://user-images.githubusercontent.com/82437913/216024559-574963fc-44cb-467a-91ee-9942fe96a6ef.png)

the next button in search:
its weird, after pressing it the 1 disappears but when clicking next again the 1 reappears, also the amount of  videos on this page is restricted (also applies to homepage and videos, the full subscribed channels arent shown, it just stops after a certain amount of videos)
![the enxt button](https://user-images.githubusercontent.com/82437913/216024785-585a64e5-b65c-4459-91c1-4059a017057f.png)

on a video:
**Blue:**
when liking a video, one side of the button highlight is cut off, the side between like and dislike, this does only apply to the like button, not dislike, it works fine

**Orange:**
this button kinda works... but its weird

**Red:**
It does nothing. at all
![buttons](https://user-images.githubusercontent.com/82437913/216025828-fdeeb6b7-ef6d-4018-aae9-a742a74507a2.PNG)

**Comment by Mali357** [comment]
edit: dropdown menus dont work

**Comment by doglust** [comment]
replying to comments also appears not to work at all

**Comment by Mali357** [comment]
also comment answers arent there and you cant react (like/dislike) comments, also no replies

> replying to comments also appears not to work at all

**Comment by Mali357** [comment]
also when searching and clicking on 1, it brings you to this URL

https://www.youtube.com/web/20121031234035/http:/www.youtube.com/results?page=1

Which is 404

**Comment by ciulinuwu** [comment]
> replying to comments also appears not to work at all

If comments are not working, please open an issue detailing your problem there.

**Comment by ciulinuwu** [comment]
@doglust If comments are not working, please open an issue detailing your problem there.

**Comment by ciulinuwu** [comment]
> so there are a few things that are i guess just placeholders or are a bug, idk. starting off with the bottom of the page: undefined is present, also no dropdown menu, the same with english and safety options, being not funcional. ![nothing bro y](https://user-images.githubusercontent.com/82437913/216024559-574963fc-44cb-467a-91ee-9942fe96a6ef.png)
> 
> the next button in search: its weird, after pressing it the 1 disappears but when clicking next again the 1 reappears, also the amount of videos on this page is restricted (also applies to homepage and videos, the full subscribed channels arent shown, it just stops after a certain amount of videos) ![the enxt button](https://user-images.githubusercontent.com/82437913/216024785-585a64e5-b65c-4459-91c1-4059a017057f.png)
> 
> on a video: **Blue:** when liking a video, one side of the button highlight is cut off, the side between like and dislike, this does only apply to the like button, not dislike, it works fine
> 
> **Orange:** this button kinda works... but its weird
> 
> **Red:** It does nothing. at all ![buttons](https://user-images.githubusercontent.com/82437913/216025828-fdeeb6b7-ef6d-4018-aae9-a742a74507a2.PNG)

@Mali357 I have not implemented everything, because my focus and motivation keeps shifting. They will eventually be added.
