### ISSUE TITLE
Channel Pages only display 30 videos, there is no way of viewing the rest

### ISSUE THREAD

**Issue by UnderscoreAngel** [thistlecafe/cosmic-cat#101]
![imagen](https://user-images.githubusercontent.com/105066360/216785621-30410588-90af-4502-b8b6-118871ccbce2.png)

**Comment by ParentIsNil** [comment]
navigation buttons havent been added just wait for the next update

**Comment by ciulinuwu** [comment]
Has been added to a4113a0 :3
