### ISSUE TITLE
Excessive margin sizing

### ISSUE THREAD

**Issue by AstoriaFloyd** [thistlecafe/cosmic-cat#103]
I have a 1440p monitor, and much of the website is, just margin
![image](https://user-images.githubusercontent.com/39976417/216799499-bf4a0135-ca47-408d-9903-1622a54b256e.png)
![image](https://user-images.githubusercontent.com/39976417/216799534-f0d5aca2-6427-4e18-a695-dadbfa4e8c5e.png)

**Comment by Mali357** [comment]
just press ctrl and mouse wheel into the website, i do that too and have a 4k laptop display

**Comment by ciulinuwu** [comment]
Hi. I do not think I can do much about this.

But as Mali357 recommended, try zooming in. I will close this.
