### ISSUE TITLE
Channel name doesn't update in UI until re-logging

### ISSUE THREAD

**Issue by 4pocalipse** [thistlecafe/cosmic-cat#104]
### Type

Page Renderer

### Page URL

(any)

### Branch

main

### Version

0.6.14

### A brief description

Once you've logged in, if you change your channel username or the channel picture, it doesn't update in the UI, except if you sign out and log-in again.
In my demonstration, the old username was "apocalipse" and the new one is "valkyrja", as you can see in the console output for 'Storage' initialization and in the screenshot.

### Screenshots or videos

Demonstration:
![image](https://user-images.githubusercontent.com/60764306/216873733-5ca6139b-2999-46cb-bd3d-ff89781114d2.png)

### Console output

`Storage.init {"storageVer":20230122 
(...) 
"i18n.setup":"1","iframe":"0","channel_mode":"3","greeting_feed":"youtube","accountInfo":{"name":"apocalipse","pfp":"[https://yt3.ggpht.com/aFOsmC4ZFuFAkEfVpbAuDJ-_rqtlpTvzQWeWXs…CKeeoXxTQsheZq22B-CHITK7FAUf3yUYI=s108-c-k-c0x00ffffff-no-rj](https://yt3.ggpht.com/aFOsmC4ZFuFAkEfVpbAuDJ-_rqtlpTvzQWeWXsL3X4CKeeoXxTQsheZq22B-CHITK7FAUf3yUYI=s108-c-k-c0x00ffffff-no-rj)","email":"REDACTED"}}`

**Comment by ciulinuwu** [comment]
Hello there, thank you for reporting this issue.

I will add a checker that'll update the stored username/pfp.

**Comment by ciulinuwu** [comment]
Hi, I have released 0.6.15 which should fix this problem.

I will close this issue. If you still encounter any problems with the channel info not updating, please reopen this issue.
