### ISSUE TITLE
palemoon and greasemonkey have issues with this script

### ISSUE THREAD

**Issue by Mali357** [thistlecafe/cosmic-cat#106]
### Type

Page Renderer

### Page URL

https://www.youtube.com/results?search_query=exodus+honey&oq=&aq=&aqi=&aql=&gs_sm=&gs_upl=

### Branch

main

### Version

0.6.15 or the newest i guess...

### A brief description

no page loads, no videos, no browse, no search. homepage does and is completely useless

### Screenshots or videos

![bensound](https://user-images.githubusercontent.com/82437913/219742651-01f9e03d-afe4-4593-b225-161b8f220812.PNG)

### Console output

in the image

**Comment by ciulinuwu** [comment]
Thank you for your report. Cosmic Cat doesn't work on Pale Moon due to it not supporting optional chaining.

Optional chaining is required to keep the code short and compact, so I can't fix this thing.

I'd recommend Firefox or any Chromium browser with ES10 support.
