### ISSUE TITLE
Comments with apostrophies in them get posted wrong

### ISSUE THREAD

**Issue by millionsofplayers** [thistlecafe/cosmic-cat#108]
### Type

Page Renderer

### Page URL

Any video, just a comments bug

### Branch

main

### Version

0.6.18

### A brief description

If i want to comment something but the comment has a ' in it, it posts the comment but replaces the apostrophe with some weird characters, i forget what they're called.

screenshot is on normal youtube to show it's not just a display thing

### Screenshots or videos

https://i.imgur.com/T2QUqlz.png

### Console output

https://i.imgur.com/TLlnDyZ.png

**Comment by ciulinuwu** [comment]
Thank you for reporting this issue. I will look into it.

**Comment by ciulinuwu** [comment]
Has been fixed in a4113a0 :3
