### ISSUE TITLE
Can't scroll in watch page to see comments / other recommended videos

### ISSUE THREAD

**Issue by ameliarat** [thistlecafe/cosmic-cat#111]
### Type

Page Renderer

### Page URL

youtube.com

### Branch

main

### Version

0.6.18 

### A brief description

whenever i try to scroll down to the comments or other video recommendations on any video, it doesn't let me. furthermore, the scrollbar does not even appear.

### Screenshots or videos

![imagen](https://user-images.githubusercontent.com/122837267/220827515-ba627475-8f0c-4005-8f2a-7bcea96b41c9.png)
(see? no scrollbar)

### Console output

![imagen](https://user-images.githubusercontent.com/122837267/220827614-e0f385ba-df68-494b-9822-137cd06394ac.png)
![imagen](https://user-images.githubusercontent.com/122837267/220827624-3841a246-f5e2-4ffc-8eb0-faec2742afee.png)

**Comment by ciulinuwu** [comment]
Hi, thank you for reporting this issue.

This is certainly weird. Do you have any other extensions/userscripts enabled?

**Comment by ameliarat** [comment]
> 

nope, this is from a fresh tampermonkey extension install

**Comment by ciulinuwu** [comment]
Can you try disabling dark theme?

**Comment by ameliarat** [comment]
it sadly, didn't work
![imagen](https://user-images.githubusercontent.com/122837267/220828376-630ecc96-a5ae-468c-aa4c-3de5725d7915.png)
also, another strange quirk. the only way i got to enter to the userscript settings is by entering through youtube.com/cosmic_cat, using the youtube settings button just lets me on a blank screen

**Comment by ciulinuwu** [comment]
For Cosmic Cat's settings; the button is called "Settings" not "YouTube Settings"

Do you have Stylus/Userstyles installed? Something could be messing up the CSS.

**Comment by ameliarat** [comment]
i have neither installed, these are the only extensions i have installed
![imagen](https://user-images.githubusercontent.com/122837267/220829031-cd08765b-da2c-439d-9c7b-bb890c509de1.png)
i have no idea what could this be caused by, maybe it is because i have my computer and browser in spanish?

**Comment by ciulinuwu** [comment]
Language shouldn't be the cause of this issue.

Can you try Cosmic Cat on Chrome?

**Comment by ameliarat** [comment]
any chromium-based browser works?

**Comment by ciulinuwu** [comment]
Anything that supports ES11 should work.

**Comment by ameliarat** [comment]
![imagen](https://user-images.githubusercontent.com/122837267/220834250-9d6e3923-9635-48a4-9316-0874efb53f9e.png)
oh, it works! thanks for helping me with this.
something that weirds me out thought is that, previously, i used this exact userscript in firefox (while using linux tho so idk). I'm not very fond of using google chrome so i'll check what could i do. thanks!

**Comment by ciulinuwu** [comment]
It is definitely something disabling the scrollbar with CSS. But what it is, I do not know.

**Comment by ameliarat** [comment]
i think i will check it in depth tomorrow so i can fix it in a way or other, thanks for the help!
