### ISSUE TITLE
Playlists only plays first (topmost) video on the list and doesn't show other videos

### ISSUE THREAD

**Issue by ivanjokalov** [thistlecafe/cosmic-cat#116]
When I click on a playlist on my channel it only plays the first (topmost) video on the list and doesn't show other videos

here's an example playlist:
https://www.youtube.com/watch?v=JGwWNGJdvx8&list=PLy1bC-662HHKXOVHInxvhSRReDz0d4xCI

Here's how stock YouTube handles this situation:
![Screenshot 2023-03-01 at 22-16-25 Ed Sheeran - Shape of You (Official Music Video) - YouTube](https://user-images.githubusercontent.com/77291455/222256107-517c55d9-0dc4-4ce5-89a0-3c90db33dab3.png)

Here's how cosmic cat YouTube handles this situation:
![Screenshot 2023-03-01 at 22-17-37 Ed Sheeran - Shape of You (Official Music Video 2) - YouTube](https://user-images.githubusercontent.com/77291455/222256123-50811d50-1df6-4397-8c16-5139ae597e56.png)

Here's the console export:
[console-export-2023-3-1_22-20-53.txt](https://github.com/thistlecafe/cosmic-cat/files/10864988/console-export-2023-3-1_22-20-53.txt)

**Comment by ciulinuwu** [comment]
Hi! I have added partial support for playlists on watch page. ca245c6

I will close this issue and finish adding support tomorrow.
