### ISSUE TITLE
wont let me watch videos

### ISSUE THREAD

**Issue by torielicious** [thistlecafe/cosmic-cat#123]
short videos (under 1 minute or so) work but anything longer than that doesnt, it usually just redirects me to youtube.com/featured whenever i click on the video instead of playing the actual video :(((

**Comment by ciulinuwu** [comment]
Hi. Please make a more detailed issue using the Bug Report form here: https://github.com/thistlecafe/cosmic-cat/issues/new?assignees=&labels=&template=bug-issue.yml
