### ISSUE TITLE
wont let me watch videos blehh

### ISSUE THREAD

**Issue by torielicious** [thistlecafe/cosmic-cat#124]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch/featured

### Branch

beta

### Version

0.6.26

### A brief description

whenever i try to watch a video thats longer than 5 minutes or so it doesnt work, it just shoes a blank screen with the footer.
shorter videos work fine however, i tried turning the iframe player off and on but that doesnt seem to make a difference :(

### Screenshots or videos

<img width="960" alt="bleh" src="https://user-images.githubusercontent.com/128639832/227031239-67e1bd76-f3ba-441a-880b-0e20ac64d4cf.PNG">

### Console output

<img width="417" alt="console" src="https://user-images.githubusercontent.com/128639832/227031500-d9d6fa81-f588-433d-a6c4-c7c5f259d589.PNG">

**Comment by ciulinuwu** [comment]
Hi, thank you for reporting this issue.

Can you please provide some examples of videos not working and how you ended up on `/watch/featured`?

**Comment by torielicious** [comment]
https://www.youtube.com/watch?v=kBtT08QuuZw
https://www.youtube.com/watch?v=TQahWf8w1rk
https://www.youtube.com/watch?v=IPFnWoYy_8w
https://www.youtube.com/watch?v=homJ9pE-OCc
there is more, but these ones kinda give a main idea of what doesnt wanna work

**Comment by ciulinuwu** [comment]
Hi, are you using an adblocker? if so, which one?

**Comment by ciulinuwu** [comment]
Can you please try using uBlock Origin instead?

**Comment by uy813** [comment]
> https://www.youtube.com/watch?v=kBtT08QuuZw https://www.youtube.com/watch?v=TQahWf8w1rk https://www.youtube.com/watch?v=IPFnWoYy_8w https://www.youtube.com/watch?v=homJ9pE-OCc there is more, but these ones kinda give a main idea of what doesnt wanna work

try copy link address and then paste it on /watch/featured
