### ISSUE TITLE
Video load

### ISSUE THREAD

**Issue by CubeMan1200** [thistlecafe/cosmic-cat#129]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch/featured

### Branch

beta

### Version

0.6.29

### A brief description

Sometimes if i open a video from the home page or everywhere else, i just got this page you see in the screenshot. And the URL changes to https://www.youtube.com/watch/featured every time. (Sorry for my english)

### Screenshots or videos

![bug](https://user-images.githubusercontent.com/127251339/227974747-4c1f0670-a53b-46b9-accd-126b1d29ef8e.png)

### Console output

[www.youtube.com-1679929627154.log](https://github.com/thistlecafe/cosmic-cat/files/11080166/www.youtube.com-1679929627154.log)

**Comment by nope312** [comment]
i have this exact problem too

**Comment by ciulinuwu** [comment]
Hi. Are you using an adblocker? if so, which one?
