### ISSUE TITLE
Main page is broken

### ISSUE THREAD

**Issue by NassFas** [thistlecafe/cosmic-cat#131]
### Type

Page Renderer

### Page URL

www.youtube.com

### Branch

main

### Version

0.6.30

### A brief description

Upon accessing the YouTube homepage (and any other pages), only the white background and favicon with tab text are loaded. It is worth noting that this has worked seamlessly in the past. It's a bit of a mystery as to why this has occurred out of the blue, and I'm not entirely sure what could have led to this outcome. The presence of a redirect to www.youtube.com/cosmic_cat leads me to suspect that there could be a correlation with cosmic cat settings, but this is just a tentative observation. The browser under consideration is Microsoft Edge, with version number 111.0.1661.54, while the operating system is Windows 11, at build 22000.282.
### Screenshots or videos

![Screenshot 2023-03-30 154237](https://user-images.githubusercontent.com/98911546/228890963-3dfba24e-1d52-400e-b129-fd42c206945a.png)

### Console output

![Screenshot 2023-03-30 154352](https://user-images.githubusercontent.com/98911546/228891440-0d9d1e1c-54ef-4756-a2a2-c26e0f22d265.png)

**Comment by ciulinuwu** [comment]
Hi. We apologize for the inconvenience. We've released an update that should fix this issue, can you please check it out? [1581262](https://github.com/thistlecafe/cosmic-cat/commit/1581262215d138ab93b815c096df624e489cd159)

**Comment by NassFas** [comment]
The issue is fixed now, thank you for your help
