### ISSUE TITLE
How much longer do you have to fix this bug?!

### ISSUE THREAD

**Issue by uy813** [thistlecafe/cosmic-cat#132]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch/featured

### Branch

beta

### Version

0.6.31

### A brief description

same as torielicious BUT HOW MUCH LONGER DO YOU HAVE TO FIX THIS. i'm swear to god i'm going to use youtube 2013 layout again.

### Screenshots or videos

same as torielicious

### Console output

same as torielicious

**Comment by ciulinuwu** [comment]
I do not know how to fix it as I cannot recreate it. Bitching about it is not gonna change it. Feel free to use other alternatives though :)

**Comment by uy813** [comment]
> I do not know how to fix it as I cannot recreate it. Bitching about it is not gonna change it. Feel free to use other alternatives though :)

hey i know something. how about you click a video and then copy the link quickly. once the link said "youtube.com/watch/featured", paste a link. i just commented for no reason ok? dont ask.

**Comment by uy813** [comment]
> I do not know how to fix it as I cannot recreate it. Bitching about it is not gonna change it. Feel free to use other alternatives though :)

hey i think it's fixed after the update
