### ISSUE TITLE
all info on video page shows up as "undefined"

### ISSUE THREAD

**Issue by nope312** [thistlecafe/cosmic-cat#134]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch?v=

### Branch

main

### Version

latest

### A brief description

any video i go onto just has undefined everywhere

### Screenshots or videos

![und1](https://user-images.githubusercontent.com/65314830/231581356-32b67a05-1ec4-4812-b2ef-e9244e0b545b.PNG)
![und2](https://user-images.githubusercontent.com/65314830/231581357-5008b17e-9ab1-4350-aee8-b0e93aefd3e9.PNG)

### Console output

Storage.init storage has init.
general-web-content-script.js:1392 GeneralWebCS: init
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:3562 Objectalternative: {owner: {…}, time: 'LIVE', views: '44209', title: 'Tired Of Sex', id: 'r6tzjwnuclc', …}primary: {}secondary: {}[[Prototype]]: Object
r6tzjwnuclc?playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fwww.youtube.com&widgetid=1:7 Mixed Content: The page at 'https://www.youtube.com/embed/r6tzjwnuclc?playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fwww.youtube.com&widgetid=1' was loaded over HTTPS, but requested an insecure element 'http://s.ytimg.com/yts/imgbin/player-common-vfloYYly0.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
vendor.js:2 Mixed Content: The page at 'https://www.youtube.com/embed/r6tzjwnuclc?playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fwww.youtube.com&widgetid=1' was loaded over HTTPS, but requested an insecure element 'http://s.ytimg.com/yts/imgbin/player-dark-vfllzTuHQ.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
r @ vendor.js:2
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
watch:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
content.js:86 Annotation data for this video is unavailable
watch:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
content.js:309 Unable to find the video player settings menu, annotation switch not injected
(anonymous) @ content.js:309
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:193 I like this
watch:1 Uncaught (in promise) TIMEOUT
content.js:1 Uncaught (in promise) TIMEOUT
content.js:1 Uncaught (in promise) TIMEOUT
48The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:193 I dislike this
3userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:193 undefined
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:193 I like this
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:193 Share or embed this video
DevTools failed to load source map: Could not load content for chrome-extension://lijhjhlnfifgoabbihoobnfapogkcjgk/content-scripts/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/932eb6a8/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by ciulinuwu** [comment]
Hi.

Please include the full URL, thank you.

**Comment by nope312** [comment]
its on every video

**Comment by ciulinuwu** [comment]
Weird. Works for me.
![image](https://user-images.githubusercontent.com/79811506/231583095-636ad9af-9930-486d-ab4c-9e84925c7688.png)

**Comment by nope312** [comment]
wel does the console output help at all?

**Comment by ciulinuwu** [comment]
As far I can see from the limited view of the first object, it appears the data is not missing.

Could you please send the entire primary, secondary and alternative object?

**Comment by nope312** [comment]
i got it nvm

**Comment by ciulinuwu** [comment]
Glad to hear! Enjoy :)
