### ISSUE TITLE
Channel that exists goes to 404

### ISSUE THREAD

**Issue by lambda-makes-things** [thistlecafe/cosmic-cat#135]
### Type

Page Renderer

### Page URL

https://www.youtube.com/Huggbees

### Branch

main

### Version

0.6.36

### A brief description

Just wanted to see Huggbees's channel,

if you go to https://www.youtube.com/Huggbees with out cosmic cat it goes to the channel just fine

### Screenshots or videos

![スクリーンショット 2023-04-16 午後1 52 29](https://user-images.githubusercontent.com/96893300/232341561-f38da80c-bcde-4807-b009-a22ad2f85f63.png)

### Console output

![スクリーンショット 2023-04-16 午後1 53 35](https://user-images.githubusercontent.com/96893300/232341616-a0cccefa-c705-4590-8d90-f71cb5f14aab.png)

**Comment by ciulinuwu** [comment]
Will not add support for those type of channel URLs. They're stupid as fuck, and attempting to support them breaks everything. (ytInitialData is not defined)
