### ISSUE TITLE
[Watch] Page doesn't work correctly

### ISSUE THREAD

**Issue by nottakenusernametotally** [thistlecafe/cosmic-cat#91]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch?v=dQw4w9WgXcQ

### Branch

main

### Version

0.6

### A brief description

i was watching a video and this happened               

thats it

### Screenshots or videos

<img width="527" alt="Screenshot 2022-10-26 030036" src="https://user-images.githubusercontent.com/115047715/197969764-238197c9-055e-4be6-8e13-a770a1b0bf03.png">

### Console output

<img width="413" alt="Screenshot 2022-10-26 030152" src="https://user-images.githubusercontent.com/115047715/197969687-067a8cbf-6c67-40ff-bcca-1c492360428f.png">

**Comment by ciulinuwu** [comment]
Hi, thanks for reporting this!

There are known issues with the watch page and especially with copyrighted videos.

Cosmic Cat is under rewrite and will fix both issues.
